TempoCore/Source/ThirdParty/ttp_manifest.json
Update incorrect TempoThirdParty hashes for Mac, Windows, and Windows cross-compile.
=> Update TTP Hashes

TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionQueryComponent.h
Adds virtual `GetIntersectionEntranceStartOffsetIndex` and `GetIntersectionEntranceEndOffsetIndex` methods to `TempoIntersectionQueryComponent` so derived implementations can override behavior if they make different assumptions about the indexing of road splines.
=> Add Virtual GetIntersectionEntranceStart/EndIndex to TempoIntersectionQueryComponent

Scripts/SyncDeps.sh, TempoCore/Source/ThirdParty/ttp_manifest.json
We noticed an unexpected issue with the hashing algorithm used to detect changes in Tempo's third party dependencies and prompt the user to re-download them. On Mac and Windows - but not Linux - the hashes appeared to be changing over time. That was because on those platforms `ls` formats dates differently depending on how far in the past they are. This switches SyncDeps.sh to use a more robust hashing algorithm, based on `stat` instead of `ls` and updates the hashes for all platforms accordingly.
=> Use More Robust Hashing Algorithm in SyncDeps

Scripts/SyncDeps.sh, TempoCore/Source/ThirdParty/ttp_manifest.json
We observed an issue where the hash computed by SyncDeps was not consistent across environments, and the root cause was an inconsistent locale. This sets the locale consistently before running the SyncDeps script, which makes the hashes consistent.
Also updates the Linux hash, where the new locale results in a new hash. It does not seem to affect the hash on Mac, and the hash on Windows was computed with this locale.
=> Set Consistent Locale in SyncDeps

TempoCore/Scripts/GenAPI.sh
Unreal's Python seems to have it's include directory configured incorrectly (`Engine/Binaries/ThirdParty/Python3/Mac/bin/python3-config --include` returns a
path to Engine/**Binaries**/ThirdParty, but the correct include directory is in Engine/**Source**/ThirdParty). Pip may need to build certain dependencies from source, and to do so will need the correct Python include path. If users don't have the python3-dev package installed, pip won't find the required files (namely Python.h). So, we can help pip find the required files by adding the correct include directory to the `CPATH` environment variable.
=> Use CPATH to Find Python Include Dir

TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionControlComponent.cpp, TempoWorld/Source/TempoWorld/Private/TempoWorldStateServiceSubsystem.cpp, TempoWorld/Source/TempoWorld/TempoWorld.Build.cs, TempoWorld/TempoWorld.uplugin
This changes the way we identify static actors when gathering actor states to consider non-static actors to be only those that have a MovementComponent, MassAgentComponent, or MassTrafficVehicleComponent.
=> Improve Identification of Static Actors

External/Traffic/Source/MassTraffic/Private/MassTrafficLaneChange.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficLaneChangingProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficVehicleSimulationTrait.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficFragments.h, External/Traffic/Source/MassTraffic/Public/MassTrafficLaneChange.h, External/Traffic/Source/MassTraffic/Public/MassTrafficSettings.h, External/Traffic/Source/MassTraffic/Public/MassTrafficVehicleSimulationTrait.h
The `LaneChangePriorityFilters` array on the `UMassTrafficVehicleSimulationTrait` allows the user to define a set of filters (based on "Any", "All", and "Not" tags) to restrict the lanes onto which each vehicle is allowed to change.  The priority is highest for the filter at index 0 and less for each subsequent index.
=> Add mechanism to filter lane change candidates by priority on a per-EntityConfig basis.

TempoCore/Source/TempoCoreShared/Private/TempoCoreSettings.cpp, TempoCore/Source/TempoCoreShared/Public/TempoCoreSettings.h, TempoCore/Source/TempoTime/Private/TempoTimeServiceSubsystem.cpp, TempoCore/Source/TempoTime/Private/TempoTimeWidget.cpp, TempoCore/Source/TempoTime/Private/TempoTimeWorldSettings.cpp, TempoCore/Source/TempoTime/Public/TempoTimeWidget.h, TempoCore/Source/TempoTime/Public/TempoTimeWorldSettings.h
Fixes https://github.com/tempo-sim/Tempo/issues/160
The bug was introduced by https://github.com/tempo-sim/Tempo/pull/155, which removed `TempoCoreTimeSettingsChangedEvent` in favor of `UDeveloperSettings::OnSettingChanged`. It is incorrect to use this for the time settings as we support changing these settings in the packaged binary (through UI or scripting) but `OnSettingChanged` is editor only. We do not allow changing scripting settings in the packaged binary so `OnSettingChanged` is fine to use there.
While attempting to fix this bug I made related improvements:
- `TempoTimeWorldSettings` expected users to call its `SetPaused` method to pause and unpause the game. Pausing through other means would cause errors. Now `TempoTimeWorldSettings` overrides `SetPauserPlayerState` instead to …
=> Fix Time Bugs

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
Allows the TempoWorld API to get properties within structs and to set them with a `Struct.Property` nomenclature, supporting arbitrarily deep nesting of structs.
=> Add Support for Setting Properties Within Structs

TempoWorld/Source/TempoDebris/Private/TempoDebrisParameterComponent.cpp
We are always calling `TargetedPCGComponent->GenerateLocal(true);` after setting PCG parameters from the `TempoDebrisParameterComponent`. There are two issues with that:
- In Editor or PIE we don't need to call it since it's taken care of in `PCGComponent` already
- In the packaged binary we should only call it when the parameters have actually changed
This resolves both of those. The former with an `#if !WITH_EDITOR` and the latter by replacing calls to `SetPCGParameter` with the new `MaybeSetGraphParameter`, which returns true if the parameter actually changed.
=> Avoid Unnecessary Debris Regenerations

External/Traffic/Source/MassTraffic/Private/MassTrafficMovement.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficUpdateDistanceToNearestObstacleProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficVehicleSimulationTrait.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficMovement.h, External/Traffic/Source/MassTraffic/Public/MassTrafficVehicleSimulationTrait.h, TempoAgents/Source/TempoAgentsShared/Private/TempoMassAgentSyncTraits.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoMassAgentSyncTraits.h, TempoAgents/Source/TempoAgentsShared/TempoAgentsShared.Build.cs, TempoMovement/Source/TempoMovementShared/Public/TempoVehicleControlInterface.h, TempoMovement/Source/TempoVehicleControl/Public/TempoVehicleController.h, TempoMovement/Source/TempoVehicleMovement/Private/KinematicBicycleModelMovementComponent.cpp, TempoMovement/Source/TempoVehicleMovement/Private/TempoChaosWheeledVehicleMovementComponent.cpp, TempoMovement/Source/TempoVehicleMovement/Private/TempoVehicleMovement.cpp, TempoMovement/Source/TempoVehicleMovement/Private/TempoWheeledVehiclePawn.cpp, TempoMovement/Source/TempoVehicleMovement/Public/KinematicBicycleModelMovementComponent.h, TempoMovement/Source/TempoVehicleMovement/Public/TempoChaosWheeledVehicleMovementComponent.h, TempoMovement/Source/TempoVehicleMovement/Public/TempoVehicleMovement.h, TempoMovement/Source/TempoVehicleMovement/Public/TempoWheeledVehiclePawn.h, TempoMovement/Source/TempoVehicleMovement/TempoVehicleMovement.Build.cs, TempoMovement/TempoMovement.uplugin
Allows wheeled vehicle pawns to be controlled by the TempoMovement API by adding:
- `TempoChaosWheeledVehicleMovementComponent`, which implements `ITempoVehicleMovementInterface` to map normalized acceleration and steering to `ChaosWheeledVehicleMovementComponent`'s inputs
- `ATempoWheeledVehiclePawn`, which is simply an `AWheeledVehiclePawn` with the above Tempo movement component
Also adds an option to enable or disable reversing (default false) on both the new movement component and the `KinematicBicycleModelMovementComponent`.
=> Control Wheeled Vehicle Pawns with TempoMovement

TempoAgents/Source/TempoAgentsShared/Public/TempoMassAgentSyncTraits.h, TempoWorld/Source/TempoDebris/Public/PCGAssignRandomMeshAttribute.h
Fixes two build errors on Windows caused by recent changes:
- Two accidental `MASSACTORS_API`s that should be `TEMPOAGENTSSHARED_API`s
- We are using `IPCGElementWithCustomContext`, which leads to unresolved external symbols on Windows. I don't understand why. But all it does is override `IPCGElement:: CreateContext`, so we can just do that ourselves.
=> Fix Build Errors on Windows

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp, TempoWorld/Source/TempoWorld/Public/TempoActorControlServiceSubsystem.h
Changes `UTempoActorControlServiceSubsystem` to be a normal TempoWorldSubsystem not a TempoGameWorldSubsystem, to allow it to be created in the editor. Also adds a mechanism to let the game and editor versions of this subsystem hand off hosting the service.
=> Run TempoActorControlService in Editor

EngineMods/EngineMods.json, EngineMods/README.md, Scripts/InstallEngineMods.sh
There is a bug in the engine mods script. When I wrote it I think I was trying to treat the `Patch` section as an array of arrays, each of which is an ordered set of patches. So for a given type, say "plugin" you could have one array of patches for each plugin you want to modify. But that wouldn't have worked in practice, because the whole "plugins" type is already associated with only one plugin.
Instead, we can simply allow having more than one mod of each type (two "plugin" mods for example), each with their own root and array of patches.
=> Fix Bug in Engine Mods Plugin Patching

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp, TempoWorld/Source/TempoWorld/Public/ActorControl.proto
Adds the ability to set Enum properties (as FEnumProperty or FByteProperty) on Actors and Components via RPC to TempoWorld.
Confirmed working with these three common ways to make an Enum in UE:
```
UENUM(BlueprintType)
enum ETestEnumA
{
EAOne = 0,
EATwo = 1,
EAThree = 2
};
UENUM(BlueprintType)
enum class ETestEnumB : uint8
{
EBOne = 0,
EBTwo = 1,
EBThree = 2
};
UENUM(BlueprintType)
namespace ETestEnumC
{
enum Type : int32
{
ECOne = 0,
ECTwo = 1,
ECThree = 2
};
}
UCLASS()
class MYGAME_API AEnumTestActor : public AActor
{
GENERATED_BODY()
public:
UPROPERTY(EditAnywhere)
TEnumAsByte<ETestEnumA> EnumA;
UPROPERTY(EditAnywhere)
ETestEnumB EnumB;
UPROPERTY(EditAnywhere)
TEnumAsByte<ETestEnumC::Type> EnumC;
};
```
=> Add Ability to Set Enum Properties to TempoWorld

TempoWorld/Source/TempoDebris/Private/PCGCopyAttributeFromNearest.cpp
We were previously providing the definition for `PCGGather::GatherDataForPin` which is declared in PCGGather.h but not exported. But that leads to a duplicate symbol in the packaged binary, where there is a single executable. So just remove the association between our `GatherDataForPin` and `PCGGather::GatherDataForPin` by putting ours in an anonymous namespace. We also have to copy the default arguments now.
=> Use Anonymous Namespace for GatherDataForPin in PCGCopyAttributeFromNearest

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
This fixes a math error in `SpawnActor` when spawning relative to another actor, where the relative actor's rotation is not taken into account. The multiplication order is simply backwards.
=> Fix Math Error in Spawning Relative To Actor

TempoWorld/Source/TempoDebris/Private/PCGAssignRandomMeshAttribute.cpp
A `GetTypeHash` for `FPCGSelectionKey` is declared in `PCGActorSelector.h` but not exported or inlined. I'm using it in `PCGAssignRandomMeshAttribute` by re-defining it in that cpp file. But that breaks packaging because it leads to a duplicate symbol linker error. The best solution I can think of is to only re-define it when `#if WITH_EDITOR`.
=> Prevent FPCGSelectionKey Duplicate Symbol in Packaged Binary

TempoCore/README.md, TempoCore/Source/TempoCoreShared/Public/TempoCoreSettings.h, TempoCore/Source/TempoTime/Private/TempoTimeWorldSettings.cpp
Large simulation time steps can cause simulations to evolve unstably. WallClock time mode currently guarantees that time advances strictly along with the wall clock. That is a desirable feature in some contexts, such as hardware-in-the-loop simulation. However resource intensive tasks on the game thread can lead to very long time steps, and in some contexts we would rather sacrifice the wall clock guarantee than take such a large time step.
This adds a setting, `MaxWallClockTimeStep` that will limit the max time step in WallClock time mode if set to non-zero.
=> Add Setting to Limit Time Step in Wall Clock Time Mode

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
Adds support for getting the current values of array properties, supporting arrays of POD types, structs, and nested arrays. Also makes the formatting of known vs generic structs consistent.
=> Add Support for Getting Array Property Values

TempoCore/Scripts/GenAPI.sh
These are runtime dependencies and are already in setup.py, but they are also necessary at generation time. This was not the case previously, only since https://github.com/tempo-sim/Tempo/pull/146 added an `import _tempo_context` to `__init__.py`
=> Add Missing Dependencies for Generating Python API

TempoCore/Scripts/GenAPI.sh
Currently we skip recreating the TempoEnv virtual environment if the folder exists. That condition is not robust enough. If a user has moved their Unreal installation or installed a new one we need to recreate it.
Tested on Linux, Mac, and Windows
=> Recreate TempoEnv if Python Doesn't Match

TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp, TempoAgents/Source/TempoAgentsEditor/Public/TempoRoadLaneGraphSubsystem.h, TempoAgents/Source/TempoAgentsShared/Public/TempoRoadInterface.h, TempoAgents/Source/TempoAgentsShared/Public/TempoRoadModuleInterface.h
`USplineComponent` splines are cubic Hermite splines with independent leave and arrive tangents.  These will most often be used to define paths for roads and sidewalks and such.
However, the intermediate ZoneGraph representation needs to be described in terms of `FZoneShapePoint`s, which are used to describe cubic Bezier splines.
In general, exactly preserving the represented path is possible when converting between Hermite splines and Bezier splines.  However, in this case, the independent leave and arrive tangents of the Hermite spline can't be input to the `FZoneShapePoint`s because they only have one Rotation field and one TangentLength field.  So, this method of sub-sampling attempts to follow the original path precisely without taking on the work of modifying the `FZoneShapePoint` …
=> Add uniform sub-sampling along roads and road modules for better fit ZoneShapes in curvy sections.

TempoCore/Source/TempoCore/Private/TempoAssetManager.cpp, TempoCore/Source/TempoCore/Public/TempoAssetManager.h, TempoCore/Source/TempoCore/TempoCore.Build.cs, TempoCore/Source/TempoCoreShared/Public/TempoCoreSettings.h
Adds the TempoAssetManager, a custom asset manager that for now simply adds the option to package levels to individual pak chunks. The chunk IDs are chosen with a hashing scheme to keep them stable when levels are added or removed. See the comment in the code for a detailed explanation.
=> Add TempoAssetManager with Option to Package Levels to Individual Chunks

README.md, Scripts/Build.sh, Scripts/Clean.sh, Scripts/FindProjectRoot.sh, Scripts/Package.sh, Scripts/RenamePakChunks.sh, Scripts/Run.sh
Moves Build, Package, Run, and Clean scripts from TempoSample into Tempo, so we can have more control over them in our release pipeline. This required adding `FindPackageRoot.sh` (because we can no longer assume the location of the scripts relative to the uproject file). Also adds `RenamePakChunks.sh` script to rename chunks based on what levels they contain, and calls it (unless disbaled) from `Package.sh`
=> Move Convenience Scripts into Tempo, Add RenamePakChunks Script

TempoCore/Source/TempoCore/Private/TempoAssetManager.cpp
This include:
```
#include "Engine/MapBuildDataRegistry.h"
```
causes a very odd build error on Windows:
```
'UTextureCube::UpdateResourceW': method with override specifier 'override' did not override any base class methods
```
Thankfully, I think it was always debatable whether we wanted to consider packages that contained a map data build registry but no map as "level chunks", and that's the only situation that removing this would affect. So let's just remove it.
=> Remove Map Data Build Registry Which Causes Build Error on Windows

.github/workflows/build_and_package.yml
Although the paths in the "save" and "restore" actions for the build cache resolve to the same directories, they are apparently compared before resolving which is causing the cache restore to miss. Making them identical again fixes it.
=> Fix Paths in Build Cache Restore

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
Adds support for setting individual array elements in TempoWorld, via a syntax like: `MyArrayProperty[1]`. These can be nested and used with struct properties including structs with array members and arrays of structs, for example:
```
tw.set_float_property(actor="MyActor", property="OuterStructArray[0].InnerStructArray[2].FloatArray[1]", value=1.0)
```
=> Add Support for Setting Individual Array Elements in TempoWorld

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp, TempoWorld/Source/TempoWorld/Private/TempoWorldUtils.cpp, TempoWorld/Source/TempoWorld/Public/ActorControl.proto, TempoWorld/Source/TempoWorld/Public/TempoWorldUtils.h
Adds another type of object property we can set via the TempoWorld API: asset references. With this we can set asset reference properties (hard references only, for now), for example StaticMeshes, Materials, or MaterialInstances with TempoWorld.
=> Enable Setting Asset Properties via TempoWorld API

TempoMovement/Source/TempoVehicleMovement/Private/GroundSnapComponent.cpp, TempoMovement/Source/TempoVehicleMovement/Public/GroundSnapComponent.h, TempoMovement/Source/TempoVehicleMovement/TempoVehicleMovement.Build.cs
The ground snap component currently only uses a single point to determine the height and normal it will snap to. This adds two features to make it much more robust:
- First, consider heights from four corners (owner actors extents or overrides extents) instead of just the center
- Second, compute the normal as the average of the normals from the four planes formed by each set of three of those corners. But reject any of those normals that are too steep.
=> Implement Plane Fitting in GroundSnapComponent

External/Traffic/Source/MassTraffic/Private/MassTrafficUpdateIntersectionsProcessor.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficFragments.h, External/Traffic/Source/MassTraffic/Public/MassTrafficSettings.h
Also, added optional mechanism to cut a period's duration in half if no vehicles or pedestrians are immediately waiting (ie. "ready") to use its open lanes.  This feature is enabled by default.  To disable it, set `bUseHalfDurationPeriodWhenNoVehiclesOrPedestriansAreWaiting` to `false` in MassTrafficSettings.  When disabled, every period will be full duration.
=> Enable traffic light processing when no Vehicle Entities are in the World.

EngineMods/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.3, EngineMods/EngineMods.json, External/Traffic/Source/MassTraffic/Private/MassTrafficChooseNextLaneProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficLaneChange.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficLaneChangingProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficUtils.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficVehicleSimulationTrait.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficFragments.h, External/Traffic/Source/MassTraffic/Public/MassTrafficLaneChange.h, External/Traffic/Source/MassTraffic/Public/MassTrafficTypes.h, External/Traffic/Source/MassTraffic/Public/MassTrafficUtils.h, External/Traffic/Source/MassTraffic/Public/MassTrafficVehicleSimulationTrait.h, Scripts/InstallEngineMods.sh, TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp, TempoAgents/Source/TempoAgentsEditor/Private/TempoZoneGraphBuilder.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionInterface.h, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionQueryComponent.h
Adds several new features for setting up the connectivity of lanes through intersections and behavior of actors when choosing lanes.
ZoneGraph Changes:
- Adds the concept of "compatible tags", which are lane tag types that should be connected through an intersection despite not matching.
- Changes lane connectivity generation to create all lane connection combinations for turning lanes (every source to every destination), allowing the zone graph builder to filter them.
- Changes the adjacency logic to search past "spacer" lanes (lanes that have no direction) until a non-spacer lane is found.
- Moves three debug flags from hard-coded cpp cvars to project settings.
- Fixes a bug where !Forward was assumed to mean Backward, in the utility to reverse a lane profile (it didn't consider the …
=> Lane Connectivity Improvements

TempoMovement/Source/TempoVehicleMovement/Private/TempoChaosWheeledVehicleMovementComponent.cpp
Prevents vehicles from driving up onto each other or onto pawns by default by setting the wheel trace collision responses for these types to `ECR_Ignore` in the TempoChaosWheeledvehicleMovementComponent.
=> Prevent Vehicles from Driving on Each Other or Pawns by Default

TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp, TempoAgents/Source/TempoAgentsEditor/Public/TempoRoadLaneGraphSubsystem.h, TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoRoadQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoZoneGraphUtils.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoCrosswalkInterface.h, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionQueryComponent.h, TempoAgents/Source/TempoAgentsShared/Public/TempoRoadInterface.h, TempoAgents/Source/TempoAgentsShared/Public/TempoRoadQueryComponent.h, TempoAgents/Source/TempoAgentsShared/Public/TempoZoneGraphUtils.h, TempoAgents/Source/TempoAgentsShared/TempoAgentsShared.Build.cs
Enables generating ZoneShapes for crosswalks on roads. The TempoRoadQueryComponent, which is analogous to the TempoIntersectionQueryComponent, is introduced to make the implementation of TempoCrosswalkInterface on roads more convenient.
=> Enable Generating ZoneShapes for Crosswalks on Roads

.github/workflows/build_and_package.yml
Just like https://github.com/tempo-sim/Tempo/pull/198, the engine mods cache paths don't match exactly on the save and restore steps, causing a cache miss. This corrects it.
=> Correct Engine Mods Cache Paths

TempoCore/Scripts/GenAPI.sh
Avoids two warnings from pip that confuse users:
- We were trying to suppress warnings about upgrading to the latest pip version by automatically upgrading pip. This was working on Mac and Linux but not on Windows. I've reconsidered now. We don't want to automatically upgrade, we want to keep the version that came with Unreal, and simply suppress the warning. We can do that with a local pip configuration file. This adds that file in the correct location on each platform.
- We try to uninstall any existing tempo package, so we can be sure there is no stale content. But if the user doesn't already have tempo installed (for example the first time they build) they'll get a warning. This checks if tempo is installed before attempting to uninstall.
=> Avoid Warnings from Pip

TempoAgents/Source/TempoAgentsEditor/Private/TempoAgentsEditorUtils.cpp, TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp, TempoAgents/Source/TempoAgentsEditor/Private/TempoZoneGraphBuilder.cpp, TempoAgents/Source/TempoAgentsEditor/TempoAgentsEditor.Build.cs, TempoAgents/Source/TempoAgentsShared/Private/TempoAgentsWorldSubsystem.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionControlComponent.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoParkedVehicleSpawnDataGenerator.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoRoadQueryComponent.cpp, TempoCore/Source/TempoCoreShared/Public/TempoCoreUtils.h
This wraps all BP calls from CPP in a new `CallBlueprintFunction` utility, which wraps the call in an `FEditorScriptExecutionGuard` when the call is in an Editor world.
=> Wrap all Blueprint Calls from CPP in CallBlueprintFunction Utility

.github/workflows/build_and_package.yml
Github changed the naming of runners. They used to be `Github Actions...`, now they are `Github-Actions...`. Update accordingly (and detect both, in case it's not universal).
=> Correct GH Actions Runner Name

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp, TempoWorld/Source/TempoWorld/Public/ActorControl.proto
Enables setting enum arrays in TempoWorld. Also adds support for getting their values in get_*_properties
=> Enable Setting Enum Arrays in TempoWorld

EngineMods/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.5, EngineMods/EngineMods.json, TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp
Adds a new routing type for ZoneGraph, `TempoBezier`, which adjusts the tangent lengths for turning connections to make them approximately circular. Changes ZoneShapeComponent to use `TempoBezier` by default. Adds a `TempoBezierTangentLengthMultiplier` which users can use to adjust the results as needed.
=> Add TempoBezier Routing Type to ZoneGraph

Scripts/SyncDeps.sh
We no longer require a netrc file to pull third party dependencies (as we did when TempoThirdParty was private). A user reported the error `curl: (26) .netrc error: no such file` when running Setup.sh. This removes the `-n` from the curl commands, since it is no longer required.
=> Remove -n from curl Commands

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
The way we are accessing values of FEnumProperties is not correct and results in incorrect values for some enums. This changes it to copy the way it's done in engine code, using `FEnumProperty::GetUnderlyingProperty` (for example `Engine/Source/Runtime/MovieScene/Private/MovieSceneCommonHelpers.cpp`).
Also changes the way we set FEnumProperties to use `FEnumProperty::GetUnderlyingProperty`, removing the `*static_cast<int64*>` (which was effectively a `reinterpret_cast<int64>`).
=> Get and Set FEnumProperty Value Correctly

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
In `GetObjectProperty` we make the incorrect assumption that FByteProperties always represent enums. A `uint8` itself can be a UPROPERTY, and it's `Enum` member will be unset. Attempting to get the name or value of one of those as an enum will crash. This fixes it by treating `FByteProperty` as an `int` in `GetObjectProperty` if `Enum` is not set.
Also allows setting of FByteProperties via `set_int_property`, with proper bounds checking.
=> Don't Always Treat Byte Properties as Enums in TempoWorld

TempoAgents/Source/TempoAgentsShared/Private/TempoMassSpawner.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoMassSpawner.h, TempoAgents/Source/TempoAgentsShared/TempoAgentsShared.Build.cs
There is a pair of issues between MassSpawner and MassAgentSubsystem that just so happen to "cancel out" in normal operation. Deferred level loading happens to hide one of them, revealing the other. This adds workarounds for both. Refer to the comments in the code for a detailed explanation of the issues and workarounds.
=> Add Workarounds for Mass Spawn Issues

TempoAgents/Source/TempoAgentsShared/Private/TempoMassSpawner.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoMassSpawner.h, TempoCore/Source/TempoCore/Private/TempoGameMode.cpp, TempoCore/Source/TempoCore/Public/TempoGameMode.h
https://github.com/tempo-sim/Tempo/pull/230 successfully allowed agents saved in the level to be recognized by MassSpawners on BeginPlay. However agents spawned during the deferred load state will still not be recognized, as OnWorldBeginPlay runs a little too early. This fixes that by moving the registration even closer to BeginPlay, by adding a new delegate to TempoGameMode.
=> Add PreBeginPlay Event on Register Mass Agent Components On It

External/Traffic/Source/MassTraffic/Private/MassTrafficCrowdYieldProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficIntersectionSpawnDataGenerator.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficLaneChange.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficLaneMetadataProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficMovement.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficSubsystem.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficUtils.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficVehicleControlProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficYieldDeadlockProcessor.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficLaneChange.h, External/Traffic/Source/MassTraffic/Public/MassTrafficMovement.h, External/Traffic/Source/MassTraffic/Public/MassTrafficSettings.h, External/Traffic/Source/MassTraffic/Public/MassTrafficSubsystem.h, External/Traffic/Source/MassTraffic/Public/MassTrafficTypes.h, External/Traffic/Source/MassTraffic/Public/MassTrafficUtils.h, External/Traffic/Source/MassTraffic/Public/MassTrafficYieldDeadlockProcessor.h
Before this, vehicles would only be aware of the lead vehicle on any lane.
Additional support for this feature:
- Refactored yield cycle deadlock processor to operate on Lane-Entity
Pairs.
- Fixed issue where vehicles would sometimes run over pedestrians in the
crosswalk when the vehicles would enter the intersection.
- Added improved debug visualizations for yield cycle detection,
resolution, and the full state of all yielding Entities for the
current frame.
Set `MassTraffic.DebugYieldDeadlockResolution` to 1 to see them in action.
- Improved yield "stuttering" issues when vehicles are attempting to
navigate through 2-way and 1-way intersections.
- Enabled merge yield behaviors for criss-crossing lanes, originating
from the same intersection side.
- Enabled merge yield behavior for …
=> Add support for vehicles to independently yield to any other vehicle.

External/Traffic/Source/MassTraffic/Private/MassTrafficCrowdYieldProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficYieldDeadlockProcessor.cpp, TempoAgents/Source/TempoAgentsShared/Private/TempoZoneGraphStandTask.cpp
A user's project failed to build without these #includes.
=> Add Missing #includes To MassTraffic and TempoAgents

TempoSensors/Source/TempoSensorsShared/Private/TempoSceneCaptureComponent2D.cpp
`FTimerManager`'s `GetTimerRate` actually returns the period, not the rate. So we're inadvertently re-setting the timer every frame by comparing the period to the rate.
This adds `GetTimerPeriod` and uses it when both setting the timer's rate and checking it.
=> Fix Bug Due to Confusion Between Timer Rate and Period

TempoWorld/Source/TempoWorld/Private/TempoActorControlServiceSubsystem.cpp
I neglected to add a `return` when catching this unexpected property type (a C-style array).
=> Add Missing Return When Getting Object Property And ArrayDim != 1

TempoCore/Source/TempoCoreShared/Public/TempoConversion.h
Unreal's `FRotator` uses a unique rotation convention, where yaw is left handed but pitch and roll are *right handed* (all with respect to a left-handed coordinate system). 
See the [comment](https://github.com/EpicGames/UnrealEngine/commit/0b635787f74ad136a5c40663fe1c74e211608ef8#diff-2c5da1cee70a70d751b11b8dbdcb53dfd4193216884c121ead3353c9ebe29c38R31) (added in 5.1 after "experimentation") 
This means our math, which assumes all three have the same handedness, is incorrect. This corrects the mistake and adds clarifying comments to explain handedness conversions for both `FQuat` and `FRotator`.
=> Fix Rotation Conversion Bug

Dockerfile, EngineMods/5.4/Engine/Plugins/AI/MassCrowd/MassCrowd.patch.3, EngineMods/5.4/Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs.patch.1, EngineMods/EngineMods.json
We noticed an issue on Linux where, sometimes but not always, MassCrowd plugin fails to load because it cannot find the dynamic libraries of its dependent engine plugins. This issue is caused by the way we rebuild MassCrowd with Tempo mods. To rebuild it, we copy it outside the engine, apply our mods, and then copy the rebuilt plugin back in. This strategy is both desirable (it prevents dirtying the working MassCrowd plugin if our rebuild fails or is interrupted) and required (UBT refuses to re-build a plugin in the engine folder). However, UBT adds rpaths, which the MassCrowd dynamic libraries will use to search for their dependent dynamic libraries during the rebuild. These rpaths are relative to the location where the plugin is built, so when we copy it back they're wrong.
If we were …
=> Fix Issue with Rebuilt MassCrowd rpaths on Linux

Scripts/Package.sh
- On Windows the platform folder under cooked is called "Windows" not "Win64"
- There is a typo, `stagingirectory`, preventing builds from being packaged to the Packaged folder
=> Fix Two Problems in Package Script on Windows

EngineMods/5.4/Engine/Source/Programs/UnrealBuildTool/ToolChain/TempoLinuxToolChain.cs.patch.1, EngineMods/EngineMods.json
Fixes a warning in TempoLinuxToolChain.cs, by throwing instead of passing null when the cast to LinuxPlatformSDK fails (which is never expected to happen).
=> Fix Warning in TempoLinuxToolChain.cs

External/Traffic/Source/MassTraffic/Private/MassTrafficTrailerRepresentationActorManagement.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficUpdateTrailersProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficVehicleSimulationLODProcessor.cpp, External/Traffic/Source/MassTraffic/Public/MassTrafficFragments.h
The change to add support for 5.5 (https://github.com/tempo-sim/Tempo/pull/243) introduced a bug related to vehicle physics in MassTraffic plugin.  The symptom is that some vehicles drive erratically. The bug is that all vehicles have the same physics parameters. The root cause is an unnoticed difference in the way we create the physics fragment. Previously were doing this:
```
const FMassTrafficSimpleVehiclePhysicsTemplate* Template = MassTrafficSubsystem->GetOrExtractVehiclePhysicsTemplate(PhysicsParams.PhysicsVehicleTemplateActor);
const uint32 TemplateHash = UE::StructUtils::GetStructCrc32(FConstStructView::Make(*Template));
const FConstSharedStruct PhysicsSharedFragment = EntityManager.GetOrCreateConstSharedFragmentByHash<FMassTrafficVehiclePhysicsSharedParameters>(TemplateHash, …
```
=> Fix Bug Related to Hashing Physics Parameters

TempoCore/Scripts/GenProtos.sh
Fixes a bug where module names are not correctly prepended to optional custom package names on Mac. The root cause is that while `\s` is a shortcut for `:space:` on GNU (Linux) sed, it is not on BSD (Mac) sed. So, we have to use `:space:`.
=> Fix Bug with Custom Proto Package Names on Mac

EngineMods/5.4/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.5, EngineMods/5.5/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.5, EngineMods/EngineMods.json, TempoAgents/Source/TempoAgentsEditor/Private/TempoZoneGraphBuilder.cpp, TempoAgents/Source/TempoAgentsEditor/Public/TempoZoneGraphBuilder.h, TempoAgents/Source/TempoAgentsShared/Private/TempoIntersectionQueryComponent.cpp, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionInterface.h, TempoAgents/Source/TempoAgentsShared/Public/TempoIntersectionQueryComponent.h
There are currently intersection geometries that can result in lanes with no connection, creating "dead end" lanes. There are also geometries that can result in "redundant" connections, creating unnecessary merge conflicts. There are several ways these can happen, but they are generally more likely when the different roads entering and leaving an intersection have different numbers of lanes.
This makes three separate improvements to our lane filtering logic.
The first involves connections that are incorrectly identified as turning connections in TempoIntersectionQueryComponent.
- TempoIntersectionQueryComponent uses a lane-based heuristic, while ZoneShapeUtilities uses a road-based one. This can result in TempoIntersectionQueryComponent identifying different lanes within the same road as …
=> Improve Intersection Connection Filtering

.github/workflows/build_and_package.yml, .github/workflows/tempo_build_and_package.yml
The `pull_request` dispatch event does not allow PRs opened from forks (e.g. https://github.com/tempo-sim/Tempo/pull/258) to access repo secrets. This makes sense, for security. But it means that PRs from forks cannot access the Unreal docker images, and therefore cannot run our Build and Package workflow.
The `pull_request_target` dispatch event was [introduced](https://github.blog/news-insights/product-news/github-actions-improvements-for-fork-and-pull-request-workflows/) for this use case:
```
In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets.
This makes common workflows like labeling or commenting on pull requests very difficult.
In order to solve this, we’ve added …
```
=> Use pull_request_target Dispatch So PRs from Forks Can Access Secrets

TempoCore/Source/TempoCoreEditor/Private/TempoCoreEditorServiceSubsystem.cpp, TempoCore/Source/TempoCoreEditor/Public/TempoCoreEditor.proto
Adds an `overwrite` flag to the Save Level RPC.
Fixes https://github.com/tempo-sim/Tempo/issues/257
=> Add Overwrite Flag to Save Level RPC

.github/workflows/build_and_package.yml, .github/workflows/tempo_build_and_package.yml
I recently added https://github.com/tempo-sim/Tempo/pull/260 to allow forks from PRs to access repo secrets. I enabled a repo setting to require approval before running pull requests from forks in order to control which PRs secrets would be shared with.
Unfortunately, to my surprise, that setting only applies the `pull_request` trigger, and not the the `pull_request_target` trigger. So, that setting didn't actually do anything.
This adds an alternative strategy that achieves the same result I was trying for: PRs from forks must be explicitly approved, while non-fork PRs can run workflows without approval. It does so by:
- Adding an [environment](https://github.com/tempo-sim/Tempo/settings/environments/6782376989/edit) with the necessary secrets requiring approval to be used
- Using that …
=> Use fork-pr-environment in PR Workflows Triggered By Fork PRs

TempoMovement/Source/TempoVehicleMovement/Private/TempoChaosWheeledVehicleMovementComponent.cpp
We have a scheme in `TempoChaosWheeledVehicleMovementComponent` to map normalized acceleration (-1 to 1) to normalized throttle and brakes (each 0 to 1). We're using >0 current forward velocity to determine if a forwards acceleration should cause us to apply brakes (as we should if we are moving backwards) or throttle (as we should if we are stopped or moving forwards). That's preventing vehicles from applying the throttle when they have zero or very small negative forward velocities.
This changes the logic to apply throttle when forward velocity is above a small negative threshold *and* the gear is not a reverse gear.
=> Use Current Gear in Throttle Mapping

TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp
Fixes two bugs in the transform math when creating a ZoneShapePoint:
- SetRotationFromForwardAndUp expects vectors relative to the parent Actor, not relative to the ZoneShapeComponent itself
- We need to use InverseTransformVector, not InverseTransformPosition, for these
=> Fix Bugs in Transform Math When Creating ZoneShapePoints

TempoCore/Source/TempoCoreShared/Private/TempoCoreUtils.cpp
Fixes a coordinate transform bug in `UTempoCoreUtils::GetActorLocalBounds`. We were getting the transform of the actor relative to the component and then taking the inverse of that. Now we are getting the transform of the component relative to the actor directly. The two don't produce the same result when the component transform's scale has negative values.
=> Fix Coordinate Transform Bug in GetActorLocalBounds

TempoCore/Source/TempoCoreShared/Private/TempoCoreUtils.cpp, TempoWorld/Source/TempoWorld/Private/TempoWorldStateServiceSubsystem.cpp
`BodyInstance.GetBodySetup()` returns null for a SkeletalMeshComponent. To get the bounds of one you need to use its physics asset.
Also fixes a bug where the debug visualization of bounding boxes did not take scale into account.
=> Correct Calculation of Skeletal Mesh Bounds

TempoCore/Source/TempoCore/Private/TempoCoreServiceSubsystem.cpp, TempoCore/Source/TempoCore/Private/TempoWorldSettings.cpp, TempoCore/Source/TempoCore/Public/TempoCore.proto, TempoCore/Source/TempoCore/Public/TempoCoreServiceSubsystem.h, TempoCore/Source/TempoCore/Public/TempoWorldSettings.h, TempoCore/Source/TempoCoreShared/Private/TempoCoreSettings.cpp, TempoCore/Source/TempoCoreShared/Public/TempoCoreSettings.h, TempoSensors/Source/TempoSensorsShared/Private/TempoSceneCaptureComponent2D.cpp
Adds the ability to disable the main viewport render, saving any performance that would have been used to render it in situations where it is not needed. This is controllable through the TempoCore API (set_main_viewport_render_enabled) or TempoCoreSettings and the default, if not set through config or API, is determined by the presence of the `renderoffscreen` command line flag.
=> Add Ability to Disable Main Viewport Render

EngineMods/5.4/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.6, EngineMods/5.5/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.6, EngineMods/5.6/Engine/Plugins/Runtime/ZoneGraph/ZoneGraph.patch.6, TempoAgents/Source/TempoAgentsEditor/Private/TempoRoadLaneGraphSubsystem.cpp
The previous commit (https://github.com/tempo-sim/Tempo/pull/290) changed `FZoneGraphStorage` struct. That wasn't a great idea, as it broke library compatibility with plugins that depend on ZoneGraph (for example ZoneGraphAnnotations). This moves the lane profiles directly to the ZoneGraphData Actor instead.
=> Revert Change to FZoneGraphStorage Struct

EngineMods/5.5/Engine/Plugins/Runtime/StateTree/StateTree.patch.1, EngineMods/EngineMods.json, External/Traffic/Source/MassTraffic/Private/MassTrafficLightVisualizationProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficParkedVehicleVisualizationProcessor.cpp, External/Traffic/Source/MassTraffic/Private/MassTrafficTrailerVisualizationProcessor.cpp, README.md
Xcode 16.3 changed the apple clang compiler and revealed some build errors in Tempo and Unreal.
=> Fix Build Errors With XCode 16.3

TempoSensors/Source/TempoSensorsShared/Private/TempoSceneCaptureComponent2D.cpp, TempoSensors/Source/TempoSensorsShared/Public/TempoSensorsSettings.h, TempoSensors/Source/TempoSensorsShared/TempoSensorsShared.Build.cs
Since 5.5 FRayTracingScene includes buffers, StatsReadbackBuffers and FeedbackReadback, of fixed size. When only rendering the main viewport the default size (4) is sufficient. But when running potentially many scene captures per frame they can easily be overrun, leading to reuse of in-use readbacks and crashes. So in this change we are "hacking" into the persistent RayTracingScene of the scene and increasing the size of these buffers.
=> Add Workaround for Potential Buffer Overrun in FRayTracingScene

README.md, Scripts/Build.sh, Scripts/Clean.sh, Scripts/FindUnreal.sh, Scripts/InstallEngineMods.sh, Scripts/Package.sh, Scripts/Run.sh
Add FindUnreal script, making `UNREAL_ENGINE_PATH` environment variable optional on Windows and Mac.
=> Add FindUnreal Script
